# Generated by Django 4.1 on 2022-08-31 09:06

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_trailer',
            field=embed_video.fields.EmbedVideoField(default=0, null=True),
        ),
    ]
